import { NameObject } from './interfaces';
import { GenderEnum, PopularityEnum, LengthEnum } from './interfaces/enum';

export const names: NameObject[] = [
  {
    id: 1,
    name: "בן",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },
  {
    id: 2,
    name: "יעקב",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.BIBLICAL,
    length: LengthEnum.MEDIUM,
  },
  {
    id: 3,
    name: "עודד",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.MEDIUM,
  },
  {
    id: 4,
    name: "אברהם",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.BIBLICAL,
    length: LengthEnum.LONG,
  },
  {
    id: 5,
    name: "יוסי",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 6,
    name: "",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },
  {
    id: 7,
    name: "Benjamin",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.LONG,
  },
  {
    id: 8,
    name: "William",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.LONG,
  },
  {
    id: 9,
    name: "Lucus",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },
  {
    id: 10,
    name: "Harrison",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.LONG,
  },
  {
    id: 11,
    name: "Selma",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 12,
    name: "Asher",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 13,
    name: "Tucker",
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },

  {
    id: 14,
    name: "Arya",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 15,
    name: "Olivia",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },
  {
    id: 16,
    name: "Fay",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 17,
    name: "Brooklyn",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.LONG,
  },
  {
    id: 18,
    name: "Genevieve",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.LONG,
  },
  {
    id: 19,
    name: "Zoe",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },
  {
    id: 20,
    name: "Valentina",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.LONG,
  },
  {
    id: 21,
    name: "Josephine",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.LONG,
  },
  {
    id: 22,
    name: "Maya",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },
  {
    id: 23,
    name: "Everleigh",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.LONG,
  },
  {
    id: 24,
    name: "Poppy",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 25,
    name: "Maia",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 26,
    name: "Ivy",
    gender: GenderEnum.GIRL,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },

  {
    id: 27,
    name: "Jude",
    gender: GenderEnum.UNISEX,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 28,
    name: "Adrian",
    gender: GenderEnum.UNISEX,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },
  {
    id: 29,
    name: "Sunny",
    gender: GenderEnum.UNISEX,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.SHORT,
  },
  {
    id: 30,
    name: "Channing",
    gender: GenderEnum.UNISEX,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.LONG,
  },
  {
    id: 31,
    name: "Tennessee",
    gender: GenderEnum.UNISEX,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.LONG,
  },
  {
    id: 32,
    name: "Dallas",
    gender: GenderEnum.UNISEX,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },

  {
    id: 33,
    name: "Zephyr",
    gender: GenderEnum.UNISEX,
    popularity: PopularityEnum.UNIQUE,
    length: LengthEnum.LONG,
  },

  {
    id: 34,
    name: "Teri",
    gender: GenderEnum.UNISEX,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
  },
  {
    id: 35,
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.BIBLICAL,
    length: LengthEnum.LONG,
    name: 'יהושפט'
  },
  {
    id: 36,
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.BIBLICAL,
    length: LengthEnum.LONG,
    name: 'אלקנא'
  },
  {
    id: 37,
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.BIBLICAL,
    length: LengthEnum.MEDIUM,
    name: 'עזרא'
  },
  {
    id: 38,
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.BIBLICAL,
    length: LengthEnum.MEDIUM,
    name: 'יצחק'
  },
  {
    id: 39,
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.MEDIUM,
    name: 'נועם'
  },
  {
    id: 40,
    gender: GenderEnum.BOY,
    popularity: PopularityEnum.TREND,
    length: LengthEnum.SHORT,
    name: 'בן'
  }
];